export const CountryWithFlag: any[any] = {
    "Andorra": { code: "AD", flag: "🇦🇩", country: "Andorra" },
    "United Arab Emirates": { code: "AE", flag: "🇦🇪", country: "United Arab Emirates" },
    "Afghanistan": { code: "AF", flag: "🇦🇫", country: "Afghanistan" },
    "Antigua and Barbuda": { code: "AG", flag: "🇦🇬", country: "Antigua and Barbuda" },
    "Anguilla": { code: "AI", flag: "🇦🇮", country: "Anguilla" },
    "Albania": { code: "AL", flag: "🇦🇱", country: "Albania" },
    "Armenia": { code: "AM", flag: "🇦🇲", country: "Armenia" },
    "Angola": { code: "AO", flag: "🇦🇴", country: "Angola" },
    "Antarctica": { code: "AQ", flag: "🇦🇶", country: "Antarctica" },
    "Argentina": { code: "AR", flag: "🇦🇷", country: "Argentina" },
    "American Samoa": { code: "AS", flag: "🇦🇸", country: "American Samoa" },
    "Austria": { code: "AT", flag: "🇦🇹", country: "Austria" },
    "Australia": { code: "AU", flag: "🇦🇺", country: "Australia" },
    "Aruba": { code: "AW", flag: "🇦🇼", country: "Aruba" },
    "Åland Islands": { code: "AX", flag: "🇦🇽", country: "Åland Islands" },
    "Azerbaijan": { code: "AZ", flag: "🇦🇿", country: "Azerbaijan" },
    "Bosnia and Herzegovina": { code: "BA", flag: "🇧🇦", country: "Bosnia and Herzegovina" },
    "Barbados": { code: "BB", flag: "🇧🇧", country: "Barbados" },
    "Bangladesh": { code: "BD", flag: "🇧🇩", country: "Bangladesh" },
    "Belgium": { code: "BE", flag: "🇧🇪", country: "Belgium" },
    "Burkina Faso": { code: "BF", flag: "🇧🇫", country: "Burkina Faso" },
    "Bulgaria": { code: "BG", flag: "🇧🇬", country: "Bulgaria" },
    "Bahrain": { code: "BH", flag: "🇧🇭", country: "Bahrain" },
    "Burundi": { code: "BI", flag: "🇧🇮", country: "Burundi" },
    "Benin": { code: "BJ", flag: "🇧🇯", country: "Benin" },
    "Saint Barthélemy": { code: "BL", flag: "🇧🇱", country: "Saint Barthélemy" },
    "Bermuda": { code: "BM", flag: "🇧🇲", country: "Bermuda" },
    "Brunei Darussalam": { code: "BN", flag: "🇧🇳", country: "Brunei Darussalam" },
    "Bolivia": { code: "BO", flag: "🇧🇴", country: "Bolivia" },
    "Bonaire, Sint Eustatius and Saba": { code: "BQ", flag: "🇧🇶", country: "Bonaire, Sint Eustatius and Saba" },
    "Brazil": { code: "BR", flag: "🇧🇷", country: "Brazil" },
    "Bahamas": { code: "BS", flag: "🇧🇸", country: "Bahamas" },
    "Bhutan": { code: "BT", flag: "🇧🇹", country: "Bhutan" },
    "Bouvet Island": { code: "BV", flag: "🇧🇻", country: "Bouvet Island" },
    "Botswana": { code: "BW", flag: "🇧🇼", country: "Botswana" },
    "Belarus": { code: "BY", flag: "🇧🇾", country: "Belarus" },
    "Belize": { code: "BZ", flag: "🇧🇿", country: "Belize" },
    "Canada": { code: "CA", flag: "🇨🇦", country: "Canada" },
    "Cocos(Keeling) Islands": { code: "CC", flag: "🇨🇨", country: "Cocos(Keeling) Islands" },
    "Congo": { code: "CD", flag: "🇨🇩", country: "Congo" },
    "Central African Republic": { code: "CF", flag: "🇨🇫", country: "Central African Republic" },
    // "Congo": { code: "CG", flag: "🇨🇬", country: "Congo" },
    "Switzerland": { code: "CH", flag: "🇨🇭", country: "Switzerland" },
    "Côte D'Ivoire": { code: "CI", flag: "🇨🇮", country: "Côte D'Ivoire" },
    "Cook Islands": { code: "CK", flag: "🇨🇰", country: "Cook Islands" },
    "Chile": { code: "CL", flag: "🇨🇱", country: "Chile" },
    "Cameroon": { code: "CM", flag: "🇨🇲", country: "Cameroon" },
    "China": { code: "CN", flag: "🇨🇳", country: "China" },
    "Colombia": { code: "CO", flag: "🇨🇴", country: "Colombia" },
    "Costa Rica": { code: "CR", flag: "🇨🇷", country: "Costa Rica" },
    "Cuba": { code: "CU", flag: "🇨🇺", country: "Cuba" },
    "Cape Verde": { code: "CV", flag: "🇨🇻", country: "Cape Verde" },
    "Curaçao": { code: "CW", flag: "🇨🇼", country: "Curaçao" },
    "Christmas Island": { code: "CX", flag: "🇨🇽", country: "Christmas Island" },
    "Cyprus": { code: "CY", flag: "🇨🇾", country: "Cyprus" },
    "Czech Republic": { code: "CZ", flag: "🇨🇿", country: "Czech Republic" },
    "Germany": { code: "DE", flag: "🇩🇪", country: "Germany" },
    "Djibouti": { code: "DJ", flag: "🇩🇯", country: "Djibouti" },
    "Denmark": { code: "DK", flag: "🇩🇰", country: "Denmark" },
    "Dominica": { code: "DM", flag: "🇩🇲", country: "Dominica" },
    "Dominican Republic": { code: "DO", flag: "🇩🇴", country: "Dominican Republic" },
    "Algeria": { code: "DZ", flag: "🇩🇿", country: "Algeria" },
    "Ecuador": { code: "EC", flag: "🇪🇨", country: "Ecuador" },
    "Estonia": { code: "EE", flag: "🇪🇪", country: "Estonia" },
    "Egypt": { code: "EG", flag: "🇪🇬", country: "Egypt" },
    "Western Sahara": { code: "EH", flag: "🇪🇭", country: "Western Sahara" },
    "Eritrea": { code: "ER", flag: "🇪🇷", country: "Eritrea" },
    "Spain": { code: "ES", flag: "🇪🇸", country: "Spain" },
    "Ethiopia": { code: "ET", flag: "🇪🇹", country: "Ethiopia" },
    "Finland": { code: "FI", flag: "🇫🇮", country: "Finland" },
    "Fiji": { code: "FJ", flag: "🇫🇯", country: "Fiji" },
    "Falkland Islands(Malvinas)": { code: "FK", flag: "🇫🇰", country: "Falkland Islands(Malvinas)" },
    "Micronesia": { code: "FM", flag: "🇫🇲", country: "Micronesia" },
    "Faroe Islands": { code: "FO", flag: "🇫🇴", country: "Faroe Islands" },
    "France": { code: "FR", flag: "🇫🇷", country: "France" },
    "Gabon": { code: "GA", flag: "🇬🇦", country: "Gabon" },
    "United Kingdom": { code: "GB", flag: "🇬🇧", country: "United Kingdom" },
    "Grenada": { code: "GD", flag: "🇬🇩", country: "Grenada" },
    "Georgia": { code: "GE", flag: "🇬🇪", country: "Georgia" },
    "French Guiana": { code: "GF", flag: "🇬🇫", country: "French Guiana" },
    "Guernsey": { code: "GG", flag: "🇬🇬", country: "Guernsey" },
    "Ghana": { code: "GH", flag: "🇬🇭", country: "Ghana" },
    "Gibraltar": { code: "GI", flag: "🇬🇮", country: "Gibraltar" },
    "Greenland": { code: "GL", flag: "🇬🇱", country: "Greenland" },
    "Gambia": { code: "GM", flag: "🇬🇲", country: "Gambia" },
    "Guinea": { code: "GN", flag: "🇬🇳", country: "Guinea" },
    "Guadeloupe": { code: "GP", flag: "🇬🇵", country: "Guadeloupe" },
    "Equatorial Guinea": { code: "GQ", flag: "🇬🇶", country: "Equatorial Guinea" },
    "Greece": { code: "GR", flag: "🇬🇷", country: "Greece" },
    "South Georgia": { code: "GS", flag: "🇬🇸", country: "South Georgia" },
    "Guatemala": { code: "GT", flag: "🇬🇹", country: "Guatemala" },
    "Guam": { code: "GU", flag: "🇬🇺", country: "Guam" },
    "Guinea - Bissau": { code: "GW", flag: "🇬🇼", country: "Guinea - Bissau" },
    "Guyana": { code: "GY", flag: "🇬🇾", country: "Guyana" },
    "Hong Kong": { code: "HK", flag: "🇭🇰", country: "Hong Kong" },
    "Heard Island and Mcdonald Islands": { code: "HM", flag: "🇭🇲", country: "Heard Island and Mcdonald Islands" },
    "Honduras": { code: "HN", flag: "🇭🇳", country: "Honduras" },
    "Croatia": { code: "HR", flag: "🇭🇷", country: "Croatia" },
    "Haiti": { code: "HT", flag: "🇭🇹", country: "Haiti" },
    "Hungary": { code: "HU", flag: "🇭🇺", country: "Hungary" },
    "Indonesia": { code: "ID", flag: "🇮🇩", country: "Indonesia" },
    "Ireland": { code: "IE", flag: "🇮🇪", country: "Ireland" },
    "Israel": { code: "IL", flag: "🇮🇱", country: "Israel" },
    "Isle of Man": { code: "IM", flag: "🇮🇲", country: "Isle of Man" },
    "India": { code: "IN", flag: "🇮🇳", country: "India" },
    "British Indian Ocean Territory": { code: "IO", flag: "🇮🇴", country: "British Indian Ocean Territory" },
    "Iraq": { code: "IQ", flag: "🇮🇶", country: "Iraq" },
    "Iran": { code: "IR", flag: "🇮🇷", country: "Iran" },
    "Iceland": { code: "IS", flag: "🇮🇸", country: "Iceland" },
    "Italy": { code: "IT", flag: "🇮🇹", country: "Italy" },
    "Jersey": { code: "JE", flag: "🇯🇪", country: "Jersey" },
    "Jamaica": { code: "JM", flag: "🇯🇲", country: "Jamaica" },
    "Jordan": { code: "JO", flag: "🇯🇴", country: "Jordan" },
    "Japan": { code: "JP", flag: "🇯🇵", country: "Japan" },
    "Kenya": { code: "KE", flag: "🇰🇪", country: "Kenya" },
    "Kyrgyzstan": { code: "KG", flag: "🇰🇬", country: "Kyrgyzstan" },
    "Cambodia": { code: "KH", flag: "🇰🇭", country: "Cambodia" },
    "Kiribati": { code: "KI", flag: "🇰🇮", country: "Kiribati" },
    "Comoros": { code: "KM", flag: "🇰🇲", country: "Comoros" },
    "Saint Kitts and Nevis": { code: "KN", flag: "🇰🇳", country: "Saint Kitts and Nevis" },
    "North Korea": { code: "KP", flag: "🇰🇵", country: "North Korea" },
    "South Korea": { code: "KR", flag: "🇰🇷", country: "South Korea" },
    "Kuwait": { code: "KW", flag: "🇰🇼", country: "Kuwait" },
    "Cayman Islands": { code: "KY", flag: "🇰🇾", country: "Cayman Islands" },
    "Kazakhstan": { code: "KZ", flag: "🇰🇿", country: "Kazakhstan" },
    "Lao People's Democratic Republic": { code: "LA", flag: "🇱🇦", country: "Lao People's Democratic Republic" },
    "Lebanon": { code: "LB", flag: "🇱🇧", country: "Lebanon" },
    "Saint Lucia": { code: "LC", flag: "🇱🇨", country: "Saint Lucia" },
    "Liechtenstein": { code: "LI", flag: "🇱🇮", country: "Liechtenstein" },
    "Sri Lanka": { code: "LK", flag: "🇱🇰", country: "Sri Lanka" },
    "Liberia": { code: "LR", flag: "🇱🇷", country: "Liberia" },
    "Lesotho": { code: "LS", flag: "🇱🇸", country: "Lesotho" },
    "Lithuania": { code: "LT", flag: "🇱🇹", country: "Lithuania" },
    "Luxembourg": { code: "LU", flag: "🇱🇺", country: "Luxembourg" },
    "Latvia": { code: "LV", flag: "🇱🇻", country: "Latvia" },
    "Libya": { code: "LY", flag: "🇱🇾", country: "Libya" },
    "Morocco": { code: "MA", flag: "🇲🇦", country: "Morocco" },
    "Monaco": { code: "MC", flag: "🇲🇨", country: "Monaco" },
    "Moldova": { code: "MD", flag: "🇲🇩", country: "Moldova" },
    "Montenegro": { code: "ME", flag: "🇲🇪", country: "Montenegro" },
    "Saint Martin(French Part)": { code: "MF", flag: "🇲🇫", country: "Saint Martin(French Part)" },
    "Madagascar": { code: "MG", flag: "🇲🇬", country: "Madagascar" },
    "Marshall Islands": { code: "MH", flag: "🇲🇭", country: "Marshall Islands" },
    "Macedonia": { code: "MK", flag: "🇲🇰", country: "Macedonia" },
    "Mali": { code: "ML", flag: "🇲🇱", country: "Mali" },
    "Myanmar": { code: "MM", flag: "🇲🇲", country: "Myanmar" },
    "Mongolia": { code: "MN", flag: "🇲🇳", country: "Mongolia" },
    "Macao": { code: "MO", flag: "🇲🇴", country: "Macao" },
    "Northern Mariana Islands": { code: "MP", flag: "🇲🇵", country: "Northern Mariana Islands" },
    "Martinique": { code: "MQ", flag: "🇲🇶", country: "Martinique" },
    "Mauritania": { code: "MR", flag: "🇲🇷", country: "Mauritania" },
    "Montserrat": { code: "MS", flag: "🇲🇸", country: "Montserrat" },
    "Malta": { code: "MT", flag: "🇲🇹", country: "Malta" },
    "Mauritius": { code: "MU", flag: "🇲🇺", country: "Mauritius" },
    "Maldives": { code: "MV", flag: "🇲🇻", country: "Maldives" },
    "Malawi": { code: "MW", flag: "🇲🇼", country: "Malawi" },
    "Mexico": { code: "MX", flag: "🇲🇽", country: "Mexico" },
    "Malaysia": { code: "MY", flag: "🇲🇾", country: "Malaysia" },
    "Mozambique": { code: "MZ", flag: "🇲🇿", country: "Mozambique" },
    "Namibia": { code: "NA", flag: "🇳🇦", country: "Namibia" },
    "New Caledonia": { code: "NC", flag: "🇳🇨", country: "New Caledonia" },
    "Niger": { code: "NE", flag: "🇳🇪", country: "Niger" },
    "Norfolk Island": { code: "NF", flag: "🇳🇫", country: "Norfolk Island" },
    "Nigeria": { code: "NG", flag: "🇳🇬", country: "Nigeria" },
    "Nicaragua": { code: "NI", flag: "🇳🇮", country: "Nicaragua" },
    "Netherlands": { code: "NL", flag: "🇳🇱", country: "Netherlands" },
    "Norway": { code: "NO", flag: "🇳🇴", country: "Norway" },
    "Nepal": { code: "NP", flag: "🇳🇵", country: "Nepal" },
    "Nauru": { code: "NR", flag: "🇳🇷", country: "Nauru" },
    "Niue": { code: "NU", flag: "🇳🇺", country: "Niue" },
    "New Zealand": { code: "NZ", flag: "🇳🇿", country: "New Zealand" },
    "Oman": { code: "OM", flag: "🇴🇲", country: "Oman" },
    "Panama": { code: "PA", flag: "🇵🇦", country: "Panama" },
    "Peru": { code: "PE", flag: "🇵🇪", country: "Peru" },
    "French Polynesia": { code: "PF", flag: "🇵🇫", country: "French Polynesia" },
    "Papua New Guinea": { code: "PG", flag: "🇵🇬", country: "Papua New Guinea" },
    "Philippines": { code: "PH", flag: "🇵🇭", country: "Philippines" },
    "Pakistan": { code: "PK", flag: "🇵🇰", country: "Pakistan" },
    "Poland": { code: "PL", flag: "🇵🇱", country: "Poland" },
    "Saint Pierre and Miquelon": { code: "PM", flag: "🇵🇲", country: "Saint Pierre and Miquelon" },
    "Pitcairn": { code: "PN", flag: "🇵🇳", country: "Pitcairn" },
    "Puerto Rico": { code: "PR", flag: "🇵🇷", country: "Puerto Rico" },
    "Palestinian Territory": { code: "PS", flag: "🇵🇸", country: "Palestinian Territory" },
    "Portugal": { code: "PT", flag: "🇵🇹", country: "Portugal" },
    "Palau": { code: "PW", flag: "🇵🇼", country: "Palau" },
    "Paraguay": { code: "PY", flag: "🇵🇾", country: "Paraguay" },
    "Qatar": { code: "QA", flag: "🇶🇦", country: "Qatar" },
    "Réunion": { code: "RE", flag: "🇷🇪", country: "Réunion" },
    "Romania": { code: "RO", flag: "🇷🇴", country: "Romania" },
    "Serbia": { code: "RS", flag: "🇷🇸", country: "Serbia" },
    "Russia": { code: "RU", flag: "🇷🇺", country: "Russia" },
    "Rwanda": { code: "RW", flag: "🇷🇼", country: "Rwanda" },
    "Saudi Arabia": { code: "SA", flag: "🇸🇦", country: "Saudi Arabia" },
    "Solomon Islands": { code: "SB", flag: "🇸🇧", country: "Solomon Islands" },
    "Seychelles": { code: "SC", flag: "🇸🇨", country: "Seychelles" },
    "Sudan": { code: "SD", flag: "🇸🇩", country: "Sudan" },
    "Sweden": { code: "SE", flag: "🇸🇪", country: "Sweden" },
    "Singapore": { code: "SG", flag: "🇸🇬", country: "Singapore" },
    "Saint Helena, Ascension and Tristan Da Cunha": { code: "SH", flag: "🇸🇭", country: "Saint Helena, Ascension and Tristan Da Cunha" },
    "Slovenia": { code: "SI", flag: "🇸🇮", country: "Slovenia" },
    "Svalbard and Jan Mayen": { code: "SJ", flag: "🇸🇯", country: "Svalbard and Jan Mayen" },
    "Slovakia": { code: "SK", flag: "🇸🇰", country: "Slovakia" },
    "Sierra Leone": { code: "SL", flag: "🇸🇱", country: "Sierra Leone" },
    "San Marino": { code: "SM", flag: "🇸🇲", country: "San Marino" },
    "Senegal": { code: "SN", flag: "🇸🇳", country: "Senegal" },
    "Somalia": { code: "SO", flag: "🇸🇴", country: "Somalia" },
    "Suriname": { code: "SR", flag: "🇸🇷", country: "Suriname" },
    "South Sudan": { code: "SS", flag: "🇸🇸", country: "South Sudan" },
    "Sao Tome and Principe": { code: "ST", flag: "🇸🇹", country: "Sao Tome and Principe" },
    "El Salvador": { code: "SV", flag: "🇸🇻", country: "El Salvador" },
    "Sint Maarten(Dutch Part)": { code: "SX", flag: "🇸🇽", country: "Sint Maarten(Dutch Part)" },
    "Syrian Arab Republic": { code: "SY", flag: "🇸🇾", country: "Syrian Arab Republic" },
    "Swaziland": { code: "SZ", flag: "🇸🇿", country: "Swaziland" },
    "Turks and Caicos Islands": { code: "TC", flag: "🇹🇨", country: "Turks and Caicos Islands" },
    "Chad": { code: "TD", flag: "🇹🇩", country: "Chad" },
    "French Southern Territories": { code: "TF", flag: "🇹🇫", country: "French Southern Territories" },
    "Togo": { code: "TG", flag: "🇹🇬", country: "Togo" },
    "Thailand": { code: "TH", flag: "🇹🇭", country: "Thailand" },
    "Tajikistan": { code: "TJ", flag: "🇹🇯", country: "Tajikistan" },
    "Tokelau": { code: "TK", flag: "🇹🇰", country: "Tokelau" },
    "Timor - Leste": { code: "TL", flag: "🇹🇱", country: "Timor - Leste" },
    "Turkmenistan": { code: "TM", flag: "🇹🇲", country: "Turkmenistan" },
    "Tunisia": { code: "TN", flag: "🇹🇳", country: "Tunisia" },
    "Tonga": { code: "TO", flag: "🇹🇴", country: "Tonga" },
    "Turkey": { code: "TR", flag: "🇹🇷", country: "Turkey" },
    "Trinidad and Tobago": { code: "TT", flag: "🇹🇹", country: "Trinidad and Tobago" },
    "Tuvalu": { code: "TV", flag: "🇹🇻", country: "Tuvalu" },
    "Taiwan": { code: "TW", flag: "🇹🇼", country: "Taiwan" },
    "Tanzania": { code: "TZ", flag: "🇹🇿", country: "Tanzania" },
    "Ukraine": { code: "UA", flag: "🇺🇦", country: "Ukraine" },
    "Uganda": { code: "UG", flag: "🇺🇬", country: "Uganda" },
    "United States Minor Outlying Islands": { code: "UM", flag: "🇺🇲", country: "United States Minor Outlying Islands" },
    "United States": { code: "US", flag: "🇺🇸", country: "United States" },
    "Uruguay": { code: "UY", flag: "🇺🇾", country: "Uruguay" },
    "Uzbekistan": { code: "UZ", flag: "🇺🇿", country: "Uzbekistan" },
    "Vatican City": { code: "VA", flag: "🇻🇦", country: "Vatican City" },
    "Saint Vincent and The Grenadines": { code: "VC", flag: "🇻🇨", country: "Saint Vincent and The Grenadines" },
    "Venezuela": { code: "VE", flag: "🇻🇪", country: "Venezuela" },
    "Virgin Islands, British": { code: "VG", flag: "🇻🇬", country: "Virgin Islands, British" },
    "Virgin Islands, U.S.": { code: "VI", flag: "🇻🇮", country: "Virgin Islands, U.S." },
    "Viet Nam": { code: "VN", flag: "🇻🇳", country: "Viet Nam" },
    "Vanuatu": { code: "VU", flag: "🇻🇺", country: "Vanuatu" },
    "Wallis and Futuna": { code: "WF", flag: "🇼🇫", country: "Wallis and Futuna" },
    "Samoa": { code: "WS", flag: "🇼🇸", country: "Samoa" },
    "Yemen": { code: "YE", flag: "🇾🇪", country: "Yemen" },
    "Mayotte": { code: "YT", flag: "🇾🇹", country: "Mayotte" },
    "South Africa": { code: "ZA", flag: "🇿🇦", country: "South Africa" },
    "Zambia": { code: "ZM", flag: "🇿🇲", country: "Zambia" },
    "Zimbabwe": { code: "ZW", flag: "🇿🇼", country: "Zimbabwe" }
}